### ISSUE TITLE
couldn't run from a clean clone

### ISSUE THREAD

**Issue by fredguth** [ef4/living-animation#1]
Just tried to clone and run.

```fredguth@campari in ~/Code/learn/living-animation (master)
$ ember -v
ember-cli: 3.1.0-beta.1
node: 6.9.1
os: darwin x64

fredguth@campari in ~/Code/learn/living-animation (master)
$ ember s
DEPRECATION: Addon "ember-data" (found at "/Users/fredguth/Code/learn/living-animation/node_modules/ember-data") is manually placing files in the legacy "modules" folder. Support for this will be removed in a future version.

/Users/fredguth/Code/learn/living-animation/src/ui/routes/tutorial-24/controller.js
  147:10  error  'positiveMod' is defined but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)


Build successful (9537ms) – Serving on http://localhost:4200/



Slowest Nodes (totalTime => 5% )              | Total (avg)
----------------------------------------------+---------------------
Babel (20)                                    | 3099ms (154 ms)
Concat (9)                                    | 1224ms (136 ms)
SimpleReplace (3)                             | 1070ms (356 ms)
TemplateCompiler (4)                          | 767ms (191 ms)
Rollup (1)                                    | 747ms
EslintValidationFilter (2)                    | 702ms (351 ms)
PostcssCompiler (2)                           | 560ms (280 ms)

App is being served by FastBoot
/Users/fredguth/Code/learn/living-animation/tmp/broccoli_merge_trees-output_path-8qLY7IKS.tmp/assets/living-animation.js:796
    (0, _qunit.test)('it leaves an animated orphan', async function (assert) {
                                                     ^^^^^
SyntaxError: missing ) after argument list
    at VMSandbox.eval (/Users/fredguth/Code/learn/living-animation/node_modules/ember-cli-fastboot/node_modules/fastboot/src/vm-sandbox.js:13:22)
    at /Users/fredguth/Code/learn/living-animation/node_modules/ember-cli-fastboot/node_modules/fastboot/src/ember-app.js:163:15
    at Array.forEach (native)
    at EmberApp.loadAppFiles (/Users/fredguth/Code/learn/living-animation/node_modules/ember-cli-fastboot/node_modules/fastboot/src/ember-app.js:160:18)
    at EmberApp.retrieveSandboxedApp (/Users/fredguth/Code/learn/living-animation/node_modules/ember-cli-fastboot/node_modules/fastboot/src/ember-app.js:201:10)
    at new EmberApp (/Users/fredguth/Code/learn/living-animation/node_modules/ember-cli-fastboot/node_modules/fastboot/src/ember-app.js:59:21)
    at FastBoot._buildEmberApp (/Users/fredguth/Code/learn/living-animation/node_modules/ember-cli-fastboot/node_modules/fastboot/src/index.js:114:17)
    at new FastBoot (/Users/fredguth/Code/learn/living-animation/node_modules/ember-cli-fastboot/node_modules/fastboot/src/index.js:52:10)
    at app.use (/Users/fredguth/Code/learn/living-animation/node_modules/ember-cli-fastboot/index.js:318:29)
    at Layer.handle [as handle_request] (/Users/fredguth/Code/learn/living-animation/node_modules/express/lib/router/layer.js:95:5)
App is being served by FastBoot
/Users/fredguth/Code/learn/living-animation/tmp/broccoli_merge_trees-output_path-8qLY7IKS.tmp/assets/living-animation.js:796
    (0, _qunit.test)('it leaves an animated orphan', async function (assert) {
                                                     ^^^^^
SyntaxError: missing ) after argument list
    at VMSandbox.eval (/Users/fredguth/Code/learn/living-animation/node_modules/ember-cli-fastboot/node_modules/fastboot/src/vm-sandbox.js:13:22)
    at /Users/fredguth/Code/learn/living-animation/node_modules/ember-cli-fastboot/node_modules/fastboot/src/ember-app.js:163:15
    at Array.forEach (native)
    at EmberApp.loadAppFiles (/Users/fredguth/Code/learn/living-animation/node_modules/ember-cli-fastboot/node_modules/fastboot/src/ember-app.js:160:18)
    at EmberApp.retrieveSandboxedApp (/Users/fredguth/Code/learn/living-animation/node_modules/ember-cli-fastboot/node_modules/fastboot/src/ember-app.js:201:10)
    at new EmberApp (/Users/fredguth/Code/learn/living-animation/node_modules/ember-cli-fastboot/node_modules/fastboot/src/ember-app.js:59:21)
    at FastBoot._buildEmberApp (/Users/fredguth/Code/learn/living-animation/node_modules/ember-cli-fastboot/node_modules/fastboot/src/index.js:114:17)
    at new FastBoot (/Users/fredguth/Code/learn/living-animation/node_modules/ember-cli-fastboot/node_modules/fastboot/src/index.js:52:10)
    at app.use (/Users/fredguth/Code/learn/living-animation/node_modules/ember-cli-fastboot/index.js:318:29)
    at Layer.handle [as handle_request] (/Users/fredguth/Code/learn/living-animation/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by ef4** [comment]
Thanks for the bug report. 

Try node >= 8, or try setting`FASTBOOT_DISABLED=true`.

I think either would avoid this problem (which is that fastboot is trying to load code into node that uses async functions).

**Comment by fredguth** [comment]
node 8 worked! Thanks
